 const mockUserInfo = {
  // id: "user_1",
  email: "m.contact@gmail.com",
  name: "Mai Chan Cuong",
};

 const mockPosts = [
  {
    // id: 'post_1',
    image: "/assets/posts/post_1.jpg",
    // category: "Website > Giải trí",
    name: "(ReactJS + NodeJS + SCSS) Sharecode Web xem phim bằng cách leak data từ API kkphim, ophim",
    price: 300000,
    viewer: 1425,
    // author: mockUserInfo,
  },
  {
    // id: 'post_2',
    image: "/assets/posts/post_2.jpg",
    // category: "Website > Giải trí",
    name: "Source code web nghe nhạc mp3 online MVC viết bằng [PHP & MySQL] có kèm bản word + slide",
    price: 350000,
    viewer: 356,
    // author: mockUserInfo,
  },
  {
    // id: 'post_3',
    image: "/assets/posts/post_3.jpg",
    // category: "Website > Bán hàng - TMĐT",
    name: "Code PHP & Mysql Website bán máy tính - đồ điện tử - linh kiện máy tính laptop",
    price: 100000,
    viewer: 1503,
    // author: mockUserInfo,
  },
  {
    // id: 'post_4',
    image: "/assets/posts/post_3.jpg",
    // category: "Website > Bán hàng - TMĐT",
    name: "Code PHP & Mysql Website bán máy tính - đồ điện tử - linh kiện máy tính laptop",
    price: 100000,
    viewer: 1503,
    // author: mockUserInfo,
  },
  {
    // id: 'post_5',
    image: "/assets/posts/post_2.jpg",
    // category: "Website > Giải trí",
    name: "Source code web nghe nhạc mp3 online MVC viết bằng [PHP & MySQL] có kèm bản word + slide",
    price: 350000,
    viewer: 356,
    // author: mockUserInfo,
  },
  {
    // id: 'post_6',
    image: "/assets/posts/post_1.jpg",
    // category: "Website > Giải trí",
    name: "(ReactJS + NodeJS + SCSS) Sharecode Web xem phim bằng cách leak data từ API kkphim, ophim",
    price: 300000,
    viewer: 1425,
    // author: mockUserInfo,
  },
  {
    // id: 'post_7',
    image: "/assets/posts/post_3.jpg",
    // category: "Website > Bán hàng - TMĐT",
    name: "Code PHP & Mysql Website bán máy tính - đồ điện tử - linh kiện máy tính laptop",
    price: 100000,
    viewer: 1503,
    // author: mockUserInfo,
  },
  {
    // id: 'post_8',
    image: "/assets/posts/post_2.jpg",
    // category: "Website > Giải trí",
    name: "Source code web nghe nhạc mp3 online MVC viết bằng [PHP & MySQL] có kèm bản word + slide",
    price: 350000,
    viewer: 356,
    // author: mockUserInfo,
  },
  {
    // id: 'post_9',
    image: "/assets/posts/post_1.jpg",
    // category: "Website > Giải trí",
    name: "(ReactJS + NodeJS + SCSS) Sharecode Web xem phim bằng cách leak data từ API kkphim, ophim",
    price: 300000,
    viewer: 1425,
    // author: mockUserInfo,
  },
  {
    // id: 'post_10',
    image: "/assets/posts/post_3.jpg",
    // category: "Website > Bán hàng - TMĐT",
    name: "Code PHP & Mysql Website bán máy tính - đồ điện tử - linh kiện máy tính laptop",
    price: 100000,
    viewer: 1503,
    // author: mockUserInfo,
  },
  {
    // id: 'post_11',
    image: "/assets/posts/post_2.jpg",
    // category: "Website > Giải trí",
    name: "Source code web nghe nhạc mp3 online MVC viết bằng [PHP & MySQL] có kèm bản word + slide",
    price: 350000,
    viewer: 356,
    // author: mockUserInfo,
  },
  {
    // id: 'post_12',
    image: "/assets/posts/post_1.jpg",
    // category: "Website > Giải trí",
    name: "(ReactJS + NodeJS + SCSS) Sharecode Web xem phim bằng cách leak data từ API kkphim, ophim",
    price: 300000,
    viewer: 1425,
    // author: mockUserInfo,
  },
];

module.exports = {
  mockPosts, mockUserInfo
}